using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TelephoneDirectory.Core.Models.Entities;

namespace TelephoneDirectory.Repository.Seeds
{
    public class CountrySeed : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.HasData(
                new Country { Id = 1, Iso = "AF", Name = "AFGHANISTAN", NiceName = "Afghanistan", Iso3 = "AFG",NumCode= 4, Active=true,PhoneCode= 93 },
                new Country { Id = 2, Iso = "AL", Name = "ALBANIA", NiceName = "Albania", Iso3 = "ALB", NumCode = 8, Active = true, PhoneCode = 355 },
                new Country { Id = 3, Iso = "DZ", Name = "ALGERIA", NiceName = "Algeria", Iso3 = "DZA", NumCode = 12, Active = true, PhoneCode = 213 },
                new Country { Id = 4, Iso = "AS", Name = "AMERICAN SAMOA", NiceName = "American Samoa", Iso3 = "ASM", NumCode = 16, Active = true, PhoneCode = 1684 },
                new Country { Id = 5, Iso = "AD", Name = "ANDORRA", NiceName = "Andorra", Iso3 = "AND", NumCode = 20, Active = true, PhoneCode = 376 },
                new Country { Id = 6, Iso = "AO", Name = "ANGOLA", NiceName = "Angola", Iso3 = "AGO", NumCode = 24, Active = true, PhoneCode = 244 },
                new Country { Id = 7, Iso = "AI", Name = "ANGUILLA", NiceName = "Anguilla", Iso3 = "AIA", NumCode = 660, Active = true, PhoneCode = 1264 },
                new Country { Id = 8, Iso = "AQ", Name = "ANTARCTICA", NiceName = "Antarctica", Iso3 = null, NumCode =0, Active = true, PhoneCode = 0 },
                new Country { Id = 9, Iso = "AG", Name = "ANTIGUA AND BARBUDA", NiceName = "Antigua and Barbuda", Iso3 = "ATG", NumCode = 28, Active = true, PhoneCode = 1268 },
                new Country { Id = 10, Iso = "AR", Name = "ARGENTINA", NiceName = "Argentina", Iso3 = "ARG", NumCode = 32, Active = true, PhoneCode = 54 },
                new Country { Id = 11, Iso = "AM", Name = "ARMENIA", NiceName = "Armenia", Iso3 = "ARM", NumCode = 51, Active = true, PhoneCode = 374 },
                new Country { Id = 12, Iso = "AW", Name = "ARUBA", NiceName = "Aruba", Iso3 = "ABW", NumCode = 533, Active = true, PhoneCode = 297 },
                new Country { Id = 13, Iso = "AU", Name = "AUSTRALIA", NiceName = "Australia", Iso3 = "AUS", NumCode = 36, Active = true, PhoneCode = 61 },
                new Country { Id = 14, Iso = "AT", Name = "AUSTRIA", NiceName = "Austria", Iso3 = "AUT", NumCode = 40, Active = true, PhoneCode = 43 },
                new Country { Id = 15, Iso = "AZ", Name = "AZERBAIJAN", NiceName = "Azerbaijan", Iso3 = "AZE", NumCode = 31, Active = true, PhoneCode = 994 },
                new Country { Id = 16, Iso = "BS", Name = "BAHAMAS", NiceName = "Bahamas", Iso3 = "BHS", NumCode = 44, Active = true, PhoneCode = 1242 },
                new Country { Id = 17, Iso = "BH", Name = "BAHRAIN", NiceName = "Bahrain", Iso3 = "BHR", NumCode = 48, Active = true, PhoneCode = 973 },
                new Country { Id = 18, Iso = "BD", Name = "BANGLADESH", NiceName = "Bangladesh", Iso3 = "BGD", NumCode = 50, Active = true, PhoneCode = 880 },
                new Country { Id = 19, Iso = "BB", Name = "BARBADOS", NiceName = "Barbados", Iso3 = "BRB", NumCode = 52, Active = true, PhoneCode = 1246 },
                new Country { Id = 20, Iso = "BY", Name = "BELARUS", NiceName = "Belarus", Iso3 = "BLR", NumCode = 112, Active = true, PhoneCode = 375 },
                new Country { Id = 21, Iso = "BE", Name = "BELGIUM", NiceName = "Belgium", Iso3 = "BEL", NumCode = 56, Active = true, PhoneCode = 32 },
                new Country { Id = 22, Iso = "BZ", Name = "BELIZE", NiceName = "Belize", Iso3 = "BLZ", NumCode = 84, Active = true, PhoneCode = 501 },
                new Country { Id = 23, Iso = "BJ", Name = "BENIN", NiceName = "Benin", Iso3 = "BEN", NumCode = 204, Active = true, PhoneCode = 229 },
                new Country { Id = 24, Iso = "BM", Name = "BERMUDA", NiceName = "Bermuda", Iso3 = "BMU", NumCode = 60, Active = true, PhoneCode = 1441 },
                new Country { Id = 25, Iso = "BT", Name = "BHUTAN", NiceName = "Bhutan", Iso3 = "BTN", NumCode = 64, Active = true, PhoneCode = 975 },
                new Country { Id = 26, Iso = "BO", Name = "BOLIVIA", NiceName = "Bolivia", Iso3 = "BOL", NumCode = 68, Active = true, PhoneCode = 591 },
                new Country { Id = 27, Iso = "BA", Name = "BOSNIA AND HERZEGOVINA", NiceName = "Bosnia and Herzegovina", Iso3 = "BIH", NumCode = 70, Active = true, PhoneCode = 387 },
                new Country { Id = 28, Iso = "BW", Name = "BOTSWANA", NiceName = "Botswana", Iso3 = "BWA", NumCode = 72, Active = true, PhoneCode = 267 },
                new Country { Id = 29, Iso = "BV", Name = "BOUVET ISLAND", NiceName = "Bouvet Island", Iso3 = null, NumCode =0, Active = true, PhoneCode = 0 },
                new Country { Id = 30, Iso = "BR", Name = "BRAZIL", NiceName = "Brazil", Iso3 = "BRA", NumCode = 76, Active = true, PhoneCode = 55 },
                new Country { Id = 31, Iso = "IO", Name = "BRITISH INDIAN OCEAN TERRITORY", NiceName = "British Indian Ocean Territory", Iso3 = null, NumCode =0, Active = true, PhoneCode = 246 },
                new Country { Id = 32, Iso = "BN", Name = "BRUNEI DARUSSALAM", NiceName = "Brunei Darussalam", Iso3 = "BRN", NumCode = 96, Active = true, PhoneCode = 673 },
                new Country { Id = 33, Iso = "BG", Name = "BULGARIA", NiceName = "Bulgaria", Iso3 = "BGR", NumCode = 100, Active = true, PhoneCode = 359 },
                new Country { Id = 34, Iso = "BF", Name = "BURKINA FASO", NiceName = "Burkina Faso", Iso3 = "BFA", NumCode = 854, Active = true, PhoneCode = 226 },
                new Country { Id = 35, Iso = "BI", Name = "BURUNDI", NiceName = "Burundi", Iso3 = "BDI", NumCode = 108, Active = true, PhoneCode = 257 },
                new Country { Id = 36, Iso = "KH", Name = "CAMBODIA", NiceName = "Cambodia", Iso3 = "KHM", NumCode = 116, Active = true, PhoneCode = 855 },
                new Country { Id = 37, Iso = "CM", Name = "CAMEROON", NiceName = "Cameroon", Iso3 = "CMR", NumCode = 120, Active = true, PhoneCode = 237 },
                new Country { Id = 38, Iso = "CA", Name = "CANADA", NiceName = "Canada", Iso3 = "CAN", NumCode = 124, Active = true, PhoneCode = 1 },
                new Country { Id = 39, Iso = "CV", Name = "CAPE VERDE", NiceName = "Cape Verde", Iso3 = "CPV", NumCode = 132, Active = true, PhoneCode = 238 },
                new Country { Id = 40, Iso = "KY", Name = "CAYMAN ISLANDS", NiceName = "Cayman Islands", Iso3 = "CYM", NumCode = 136, Active = true, PhoneCode = 1345 },
                new Country { Id = 41, Iso = "CF", Name = "CENTRAL AFRICAN REPUBLIC", NiceName = "Central African Republic", Iso3 = "CAF", NumCode = 140, Active = true, PhoneCode = 236 },
                new Country { Id = 42, Iso = "TD", Name = "CHAD", NiceName = "Chad", Iso3 = "TCD", NumCode = 148, Active = true, PhoneCode = 235 },
                new Country { Id = 43, Iso = "CL", Name = "CHILE", NiceName = "Chile", Iso3 = "CHL", NumCode = 152, Active = true, PhoneCode = 56 },
                new Country { Id = 44, Iso = "CN", Name = "CHINA", NiceName = "China", Iso3 = "CHN", NumCode = 156, Active = true, PhoneCode = 86 },
                new Country { Id = 45, Iso = "CX", Name = "CHRISTMAS ISLAND", NiceName = "Christmas Island", Iso3 = null, NumCode =0, Active = true, PhoneCode = 61 },
                new Country { Id = 46, Iso = "CC", Name = "COCOS {KEELING} ISLANDS", NiceName = "Cocos {Keeling} Islands", Iso3 = null, NumCode =0, Active = true, PhoneCode = 672 },
                new Country { Id = 47, Iso = "CO", Name = "COLOMBIA", NiceName = "Colombia", Iso3 = "COL", NumCode = 170, Active = true, PhoneCode = 57 },
                new Country { Id = 48, Iso = "KM", Name = "COMOROS", NiceName = "Comoros", Iso3 = "COM", NumCode = 174, Active = true, PhoneCode = 269 },
                new Country { Id = 49, Iso = "CG", Name = "CONGO", NiceName = "Congo", Iso3 = "COG", NumCode = 178, Active = true, PhoneCode = 242 },
                new Country { Id = 50, Iso = "CD", Name = "CONGO, THE DEMOCRATIC REPUBLIC OF THE", NiceName = "Congo, the Democratic Republic of the", Iso3 = "COD", NumCode = 180, Active = true, PhoneCode = 242 },
                new Country { Id = 51, Iso = "CK", Name = "COOK ISLANDS", NiceName = "Cook Islands", Iso3 = "COK", NumCode = 184, Active = true, PhoneCode = 682 },
                new Country { Id = 52, Iso = "CR", Name = "COSTA RICA", NiceName = "Costa Rica", Iso3 = "CRI", NumCode = 188, Active = true, PhoneCode = 506 },
                new Country { Id = 53, Iso = "CI", Name = "COTE DIVOIRE", NiceName = "Cote DIvoire", Iso3 = "CIV", NumCode = 384, Active = true, PhoneCode = 225 },
                new Country { Id = 54, Iso = "HR", Name = "CROATIA", NiceName = "Croatia", Iso3 = "HRV", NumCode = 191, Active = true, PhoneCode = 385 },
                new Country { Id = 55, Iso = "CU", Name = "CUBA", NiceName = "Cuba", Iso3 = "CUB", NumCode = 192, Active = true, PhoneCode = 53 },
                new Country { Id = 56, Iso = "CY", Name = "CYPRUS", NiceName = "Cyprus", Iso3 = "CYP", NumCode = 196, Active = true, PhoneCode = 357 },
                new Country { Id = 57, Iso = "CZ", Name = "CZECH REPUBLIC", NiceName = "Czech Republic", Iso3 = "CZE", NumCode = 203, Active = true, PhoneCode = 420 },
                new Country { Id = 58, Iso = "DK", Name = "DENMARK", NiceName = "Denmark", Iso3 = "DNK", NumCode = 208, Active = true, PhoneCode = 45 },
                new Country { Id = 59, Iso = "DJ", Name = "DJIBOUTI", NiceName = "Djibouti", Iso3 = "DJI", NumCode = 262, Active = true, PhoneCode = 253 },
                new Country { Id = 60, Iso = "DM", Name = "DOMINICA", NiceName = "Dominica", Iso3 = "DMA", NumCode = 212, Active = true, PhoneCode = 1767 },
                new Country { Id = 61, Iso = "DO", Name = "DOMINICAN REPUBLIC", NiceName = "Dominican Republic", Iso3 = "DOM", NumCode = 214, Active = true, PhoneCode = 1809 },
                new Country { Id = 62, Iso = "EC", Name = "ECUADOR", NiceName = "Ecuador", Iso3 = "ECU", NumCode = 218, Active = true, PhoneCode = 593 },
                new Country { Id = 63, Iso = "EG", Name = "EGYPT", NiceName = "Egypt", Iso3 = "EGY", NumCode = 818, Active = true, PhoneCode = 20 },
                new Country { Id = 64, Iso = "SV", Name = "EL SALVADOR", NiceName = "El Salvador", Iso3 = "SLV", NumCode = 222, Active = true, PhoneCode = 503 },
                new Country { Id = 65, Iso = "GQ", Name = "EQUATORIAL GUINEA", NiceName = "Equatorial Guinea", Iso3 = "GNQ", NumCode = 226, Active = true, PhoneCode = 240 },
                new Country { Id = 66, Iso = "ER", Name = "ERITREA", NiceName = "Eritrea", Iso3 = "ERI", NumCode = 232, Active = true, PhoneCode = 291 },
                new Country { Id = 67, Iso = "EE", Name = "ESTONIA", NiceName = "Estonia", Iso3 = "EST", NumCode = 233, Active = true, PhoneCode = 372 },
                new Country { Id = 68, Iso = "ET", Name = "ETHIOPIA", NiceName = "Ethiopia", Iso3 = "ETH", NumCode = 231, Active = true, PhoneCode = 251 },
                new Country { Id = 69, Iso = "FK", Name = "FALKLAND ISLANDS {MALVINAS}", NiceName = "Falkland Islands {Malvinas}", Iso3 = "FLK", NumCode = 238, Active = true, PhoneCode = 500 },
                new Country { Id = 70, Iso = "FO", Name = "FAROE ISLANDS", NiceName = "Faroe Islands", Iso3 = "FRO", NumCode = 234, Active = true, PhoneCode = 298 },
                new Country { Id = 71, Iso = "FJ", Name = "FIJI", NiceName = "Fiji", Iso3 = "FJI", NumCode = 242, Active = true, PhoneCode = 679 },
                new Country { Id = 72, Iso = "FI", Name = "FINLAND", NiceName = "Finland", Iso3 = "FIN", NumCode = 246, Active = true, PhoneCode = 358 },
                new Country { Id = 73, Iso = "FR", Name = "FRANCE", NiceName = "France", Iso3 = "FRA", NumCode = 250, Active = true, PhoneCode = 33 },
                new Country { Id = 74, Iso = "GF", Name = "FRENCH GUIANA", NiceName = "French Guiana", Iso3 = "GUF", NumCode = 254, Active = true, PhoneCode = 594 },
                new Country { Id = 75, Iso = "PF", Name = "FRENCH POLYNESIA", NiceName = "French Polynesia", Iso3 = "PYF", NumCode = 258, Active = true, PhoneCode = 689 },
                new Country { Id = 76, Iso = "TF", Name = "FRENCH SOUTHERN TERRITORIES", NiceName = "French Southern Territories", Iso3 = null, NumCode =0, Active = true, PhoneCode = 0 },
                new Country { Id = 77, Iso = "GA", Name = "GABON", NiceName = "Gabon", Iso3 = "GAB", NumCode = 266, Active = true, PhoneCode = 241 },
                new Country { Id = 78, Iso = "GM", Name = "GAMBIA", NiceName = "Gambia", Iso3 = "GMB", NumCode = 270, Active = true, PhoneCode = 220 },
                new Country { Id = 79, Iso = "GE", Name = "GEORGIA", NiceName = "Georgia", Iso3 = "GEO", NumCode = 268, Active = true, PhoneCode = 995 },
                new Country { Id = 80, Iso = "DE", Name = "GERMANY", NiceName = "Germany", Iso3 = "DEU", NumCode = 276, Active = true, PhoneCode = 49 },
                new Country { Id = 81, Iso = "GH", Name = "GHANA", NiceName = "Ghana", Iso3 = "GHA", NumCode = 288, Active = true, PhoneCode = 233 },
                new Country { Id = 82, Iso = "GI", Name = "GIBRALTAR", NiceName = "Gibraltar", Iso3 = "GIB", NumCode = 292, Active = true, PhoneCode = 350 },
                new Country { Id = 83, Iso = "GR", Name = "GREECE", NiceName = "Greece", Iso3 = "GRC", NumCode = 300, Active = true, PhoneCode = 30 },
                new Country { Id = 84, Iso = "GL", Name = "GREENLAND", NiceName = "Greenland", Iso3 = "GRL", NumCode = 304, Active = true, PhoneCode = 299 },
                new Country { Id = 85, Iso = "GD", Name = "GRENADA", NiceName = "Grenada", Iso3 = "GRD", NumCode = 308, Active = true, PhoneCode = 1473 },
                new Country { Id = 86, Iso = "GP", Name = "GUADELOUPE", NiceName = "Guadeloupe", Iso3 = "GLP", NumCode = 312, Active = true, PhoneCode = 590 },
                new Country { Id = 87, Iso = "GU", Name = "GUAM", NiceName = "Guam", Iso3 = "GUM", NumCode = 316, Active = true, PhoneCode = 1671 },
                new Country { Id = 88, Iso = "GT", Name = "GUATEMALA", NiceName = "Guatemala", Iso3 = "GTM", NumCode = 320, Active = true, PhoneCode = 502 },
                new Country { Id = 89, Iso = "GN", Name = "GUINEA", NiceName = "Guinea", Iso3 = "GIN", NumCode = 324, Active = true, PhoneCode = 224 },
                new Country { Id = 90, Iso = "GW", Name = "GUINEA-BISSAU", NiceName = "Guinea-Bissau", Iso3 = "GNB", NumCode = 624, Active = true, PhoneCode = 245 },
                new Country { Id = 91, Iso = "GY", Name = "GUYANA", NiceName = "Guyana", Iso3 = "GUY", NumCode = 328, Active = true, PhoneCode = 592 },
                new Country { Id = 92, Iso = "HT", Name = "HAITI", NiceName = "Haiti", Iso3 = "HTI", NumCode = 332, Active = true, PhoneCode = 509 },
                new Country { Id = 93, Iso = "HM", Name = "HEARD ISLAND AND MCDONALD ISLANDS", NiceName = "Heard Island and Mcdonald Islands", Iso3 =null, NumCode =0, Active = true, PhoneCode = 0 },
                new Country { Id = 94, Iso = "VA", Name = "HOLY SEE {VATICAN CITY STATE}", NiceName = "Holy See {Vatican City State}", Iso3 = "VAT", NumCode = 336, Active = true, PhoneCode = 39 },
                new Country { Id = 95, Iso = "HN", Name = "HONDURAS", NiceName = "Honduras", Iso3 = "HND", NumCode = 340, Active = true, PhoneCode = 504 },
                new Country { Id = 96, Iso = "HK", Name = "HONG KONG", NiceName = "Hong Kong", Iso3 = "HKG", NumCode = 344, Active = true, PhoneCode = 852 },
                new Country { Id = 97, Iso = "HU", Name = "HUNGARY", NiceName = "Hungary", Iso3 = "HUN", NumCode = 348, Active = true, PhoneCode = 36 },
                new Country { Id = 98, Iso = "IS", Name = "ICELAND", NiceName = "Iceland", Iso3 = "ISL", NumCode = 352, Active = true, PhoneCode = 354 },
                new Country { Id = 99, Iso = "IN", Name = "INDIA", NiceName = "India", Iso3 = "IND", NumCode = 356, Active = true, PhoneCode = 91 },
                new Country { Id = 100, Iso = "ID", Name = "INDONESIA", NiceName = "Indonesia", Iso3 = "IDN", NumCode = 360, Active = true, PhoneCode = 62 },
                new Country { Id = 101, Iso = "IR", Name = "IRAN, ISLAMIC REPUBLIC OF", NiceName = "Iran, Islamic Republic of", Iso3 = "IRN", NumCode = 364, Active = true, PhoneCode = 98 },
                new Country { Id = 102, Iso = "IQ", Name = "IRAQ", NiceName = "Iraq", Iso3 = "IRQ", NumCode = 368, Active = true, PhoneCode = 964 },
                new Country { Id = 103, Iso = "IE", Name = "IRELAND", NiceName = "Ireland", Iso3 = "IRL", NumCode = 372, Active = true, PhoneCode = 353 },
                new Country { Id = 104, Iso = "IL", Name = "ISRAEL", NiceName = "Israel", Iso3 = "ISR", NumCode = 376, Active = true, PhoneCode = 972 },
                new Country { Id = 105, Iso = "IT", Name = "ITALY", NiceName = "Italy", Iso3 = "ITA", NumCode = 380, Active = true, PhoneCode = 39 },
                new Country { Id = 106, Iso = "JM", Name = "JAMAICA", NiceName = "Jamaica", Iso3 = "JAM", NumCode = 388, Active = true, PhoneCode = 1876 },
                new Country { Id = 107, Iso = "JP", Name = "JAPAN", NiceName = "Japan", Iso3 = "JPN", NumCode = 392, Active = true, PhoneCode = 81 },
                new Country { Id = 108, Iso = "JO", Name = "JORDAN", NiceName = "Jordan", Iso3 = "JOR", NumCode = 400, Active = true, PhoneCode = 962 },
                new Country { Id = 109, Iso = "KZ", Name = "KAZAKHSTAN", NiceName = "Kazakhstan", Iso3 = "KAZ", NumCode = 398, Active = true, PhoneCode = 7 },
                new Country { Id = 110, Iso = "KE", Name = "KENYA", NiceName = "Kenya", Iso3 = "KEN", NumCode = 404, Active = true, PhoneCode = 254 },
                new Country { Id = 111, Iso = "KI", Name = "KIRIBATI", NiceName = "Kiribati", Iso3 = "KIR", NumCode = 296, Active = true, PhoneCode = 686 },
                new Country { Id = 112, Iso = "KP", Name = "KOREA, DEMOCRATIC PEOPLES REPUBLIC OF", NiceName = "Korea, Democratic Peoples Republic of", Iso3 = "PRK", NumCode = 408, Active = true, PhoneCode = 850 },
                new Country { Id = 113, Iso = "KR", Name = "KOREA, REPUBLIC OF", NiceName = "Korea, Republic of", Iso3 = "KOR", NumCode = 410, Active = true, PhoneCode = 82 },
                new Country { Id = 114, Iso = "KW", Name = "KUWAIT", NiceName = "Kuwait", Iso3 = "KWT", NumCode = 414, Active = true, PhoneCode = 965 },
                new Country { Id = 115, Iso = "KG", Name = "KYRGYZSTAN", NiceName = "Kyrgyzstan", Iso3 = "KGZ", NumCode = 417, Active = true, PhoneCode = 996 },
                new Country { Id = 116, Iso = "LA", Name = "LAO PEOPLE'S DEMOCRATIC REPUBLIC", NiceName = "Lao Peoples Democratic Republic", Iso3 = "LAO", NumCode = 418, Active = true, PhoneCode = 856 },
                new Country { Id = 117, Iso = "LV", Name = "LATVIA", NiceName = "Latvia", Iso3 = "LVA", NumCode = 428, Active = true, PhoneCode = 371 },
                new Country { Id = 118, Iso = "LB", Name = "LEBANON", NiceName = "Lebanon", Iso3 = "LBN", NumCode = 422, Active = true, PhoneCode = 961 },
                new Country { Id = 119, Iso = "LS", Name = "LESOTHO", NiceName = "Lesotho", Iso3 = "LSO", NumCode = 426, Active = true, PhoneCode = 266 },
                new Country { Id = 120, Iso = "LR", Name = "LIBERIA", NiceName = "Liberia", Iso3 = "LBR", NumCode = 430, Active = true, PhoneCode = 231 },
                new Country { Id = 121, Iso = "LY", Name = "LIBYAN ARAB JAMAHIRIYA", NiceName = "Libyan Arab Jamahiriya", Iso3 = "LBY", NumCode = 434, Active = true, PhoneCode = 218 },
                new Country { Id = 122, Iso = "LI", Name = "LIECHTENSTEIN", NiceName = "Liechtenstein", Iso3 = "LIE", NumCode = 438, Active = true, PhoneCode = 423 },
                new Country { Id = 123, Iso = "LT", Name = "LITHUANIA", NiceName = "Lithuania", Iso3 = "LTU", NumCode = 440, Active = true, PhoneCode = 370 },
                new Country { Id = 124, Iso = "LU", Name = "LUXEMBOURG", NiceName = "Luxembourg", Iso3 = "LUX", NumCode = 442, Active = true, PhoneCode = 352 },
                new Country { Id = 125, Iso = "MO", Name = "MACAO", NiceName = "Macao", Iso3 = "MAC", NumCode = 446, Active = true, PhoneCode = 853 },
                new Country { Id = 126, Iso = "MK", Name = "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", NiceName = "Macedonia, the Former Yugoslav Republic of", Iso3 = "MKD", NumCode = 807, Active = true, PhoneCode = 389 },
                new Country { Id = 127, Iso = "MG", Name = "MADAGASCAR", NiceName = "Madagascar", Iso3 = "MDG", NumCode = 450, Active = true, PhoneCode = 261 },
                new Country { Id = 128, Iso = "MW", Name = "MALAWI", NiceName = "Malawi", Iso3 = "MWI", NumCode = 454, Active = true, PhoneCode = 265 },
                new Country { Id = 129, Iso = "MY", Name = "MALAYSIA", NiceName = "Malaysia", Iso3 = "MYS", NumCode = 458, Active = true, PhoneCode = 60 },
                new Country { Id = 130, Iso = "MV", Name = "MALDIVES", NiceName = "Maldives", Iso3 = "MDV", NumCode = 462, Active = true, PhoneCode = 960 },
                new Country { Id = 131, Iso = "ML", Name = "MALI", NiceName = "Mali", Iso3 = "MLI", NumCode = 466, Active = true, PhoneCode = 223 },
                new Country { Id = 132, Iso = "MT", Name = "MALTA", NiceName = "Malta", Iso3 = "MLT", NumCode = 470, Active = true, PhoneCode = 356 },
                new Country { Id = 133, Iso = "MH", Name = "MARSHALL ISLANDS", NiceName = "Marshall Islands", Iso3 = "MHL", NumCode = 584, Active = true, PhoneCode = 692 },
                new Country { Id = 134, Iso = "MQ", Name = "MARTINIQUE", NiceName = "Martinique", Iso3 = "MTQ", NumCode = 474, Active = true, PhoneCode = 596 },
                new Country { Id = 135, Iso = "MR", Name = "MAURITANIA", NiceName = "Mauritania", Iso3 = "MRT", NumCode = 478, Active = true, PhoneCode = 222 },
                new Country { Id = 136, Iso = "MU", Name = "MAURITIUS", NiceName = "Mauritius", Iso3 = "MUS", NumCode = 480, Active = true, PhoneCode = 230 },
                new Country { Id = 137, Iso = "YT", Name = "MAYOTTE", NiceName = "Mayotte", Iso3 = null, NumCode =0, Active = true, PhoneCode = 269 },
                new Country { Id = 138, Iso = "MX", Name = "MEXICO", NiceName = "Mexico", Iso3 = "MEX", NumCode = 484, Active = true, PhoneCode = 52 },
                new Country { Id = 139, Iso = "FM", Name = "MICRONESIA, FEDERATED STATES OF", NiceName = "Micronesia, Federated States of", Iso3 = "FSM", NumCode = 583, Active = true, PhoneCode = 691 },
                new Country { Id = 140, Iso = "MD", Name = "MOLDOVA, REPUBLIC OF", NiceName = "Moldova, Republic of", Iso3 = "MDA", NumCode = 498, Active = true, PhoneCode = 373 },
                new Country { Id = 141, Iso = "MC", Name = "MONACO", NiceName = "Monaco", Iso3 = "MCO", NumCode = 492, Active = true, PhoneCode = 377 },
                new Country { Id = 142, Iso = "MN", Name = "MONGOLIA", NiceName = "Mongolia", Iso3 = "MNG", NumCode = 496, Active = true, PhoneCode = 976 },
                new Country { Id = 143, Iso = "MS", Name = "MONTSERRAT", NiceName = "Montserrat", Iso3 = "MSR", NumCode = 500, Active = true, PhoneCode = 1664 },
                new Country { Id = 144, Iso = "MA", Name = "MOROCCO", NiceName = "Morocco", Iso3 = "MAR", NumCode = 504, Active = true, PhoneCode = 212 },
                new Country { Id = 145, Iso = "MZ", Name = "MOZAMBIQUE", NiceName = "Mozambique", Iso3 = "MOZ", NumCode = 508, Active = true, PhoneCode = 258 },
                new Country { Id = 146, Iso = "MM", Name = "MYANMAR", NiceName = "Myanmar", Iso3 = "MMR", NumCode = 104, Active = true, PhoneCode = 95 },
                new Country { Id = 147, Iso = "NA", Name = "NAMIBIA", NiceName = "Namibia", Iso3 = "NAM", NumCode = 516, Active = true, PhoneCode = 264 },
                new Country { Id = 148, Iso = "NR", Name = "NAURU", NiceName = "Nauru", Iso3 = "NRU", NumCode = 520, Active = true, PhoneCode = 674 },
                new Country { Id = 149, Iso = "NP", Name = "NEPAL", NiceName = "Nepal", Iso3 = "NPL", NumCode = 524, Active = true, PhoneCode = 977 },
                new Country { Id = 150, Iso = "NL", Name = "NETHERLANDS", NiceName = "Netherlands", Iso3 = "NLD", NumCode = 528, Active = true, PhoneCode = 31 },
                new Country { Id = 151, Iso = "AN", Name = "NETHERLANDS ANTILLES", NiceName = "Netherlands Antilles", Iso3 = "ANT", NumCode = 530, Active = true, PhoneCode = 599 },
                new Country { Id = 152, Iso = "NC", Name = "NEW CALEDONIA", NiceName = "New Caledonia", Iso3 = "NCL", NumCode = 540, Active = true, PhoneCode = 687 },
                new Country { Id = 153, Iso = "NZ", Name = "NEW ZEALAND", NiceName = "New Zealand", Iso3 = "NZL", NumCode = 554, Active = true, PhoneCode = 64 },
                new Country { Id = 154, Iso = "NI", Name = "NICARAGUA", NiceName = "Nicaragua", Iso3 = "NIC", NumCode = 558, Active = true, PhoneCode = 505 },
                new Country { Id = 155, Iso = "NE", Name = "NIGER", NiceName = "Niger", Iso3 = "NER", NumCode = 562, Active = true, PhoneCode = 227 },
                new Country { Id = 156, Iso = "NG", Name = "NIGERIA", NiceName = "Nigeria", Iso3 = "NGA", NumCode = 566, Active = true, PhoneCode = 234 },
                new Country { Id = 157, Iso = "NU", Name = "NIUE", NiceName = "Niue", Iso3 = "NIU", NumCode = 570, Active = true, PhoneCode = 683 },
                new Country { Id = 158, Iso = "NF", Name = "NORFOLK ISLAND", NiceName = "Norfolk Island", Iso3 = "NFK", NumCode = 574, Active = true, PhoneCode = 672 },
                new Country { Id = 159, Iso = "MP", Name = "NORTHERN MARIANA ISLANDS", NiceName = "Northern Mariana Islands", Iso3 = "MNP", NumCode = 580, Active = true, PhoneCode = 1670 },
                new Country { Id = 160, Iso = "NO", Name = "NORWAY", NiceName = "Norway", Iso3 = "NOR", NumCode = 578, Active = true, PhoneCode = 47 },
                new Country { Id = 161, Iso = "OM", Name = "OMAN", NiceName = "Oman", Iso3 = "OMN", NumCode = 512, Active = true, PhoneCode = 968 },
                new Country { Id = 162, Iso = "PK", Name = "PAKISTAN", NiceName = "Pakistan", Iso3 = "PAK", NumCode = 586, Active = true, PhoneCode = 92 },
                new Country { Id = 163, Iso = "PW", Name = "PALAU", NiceName = "Palau", Iso3 = "PLW", NumCode = 585, Active = true, PhoneCode = 680 },
                new Country { Id = 164, Iso = "PS", Name = "PALESTINIAN TERRITORY, OCCUPIED", NiceName = "Palestinian Territory, Occupied", Iso3 =null, NumCode =0, Active = true, PhoneCode = 970 },
                new Country { Id = 165, Iso = "PA", Name = "PANAMA", NiceName = "Panama", Iso3 = "PAN", NumCode = 591, Active = true, PhoneCode = 507 },
                new Country { Id = 166, Iso = "PG", Name = "PAPUA NEW GUINEA", NiceName = "Papua New Guinea", Iso3 = "PNG", NumCode = 598, Active = true, PhoneCode = 675 },
                new Country { Id = 167, Iso = "PY", Name = "PARAGUAY", NiceName = "Paraguay", Iso3 = "PRY", NumCode = 600, Active = true, PhoneCode = 595 },
                new Country { Id = 168, Iso = "PE", Name = "PERU", NiceName = "Peru", Iso3 = "PER", NumCode = 604, Active = true, PhoneCode = 51 },
                new Country { Id = 169, Iso = "PH", Name = "PHILIPPINES", NiceName = "Philippines", Iso3 = "PHL", NumCode = 608, Active = true, PhoneCode = 63 },
                new Country { Id = 170, Iso = "PN", Name = "PITCAIRN", NiceName = "Pitcairn", Iso3 = "PCN", NumCode = 612, Active = true, PhoneCode = 0 },
                new Country { Id = 171, Iso = "PL", Name = "POLAND", NiceName = "Poland", Iso3 = "POL", NumCode = 616, Active = true, PhoneCode = 48 },
                new Country { Id = 172, Iso = "PT", Name = "PORTUGAL", NiceName = "Portugal", Iso3 = "PRT", NumCode = 620, Active = true, PhoneCode = 351 },
                new Country { Id = 173, Iso = "PR", Name = "PUERTO RICO", NiceName = "Puerto Rico", Iso3 = "PRI", NumCode = 630, Active = true, PhoneCode = 1787 },
                new Country { Id = 174, Iso = "QA", Name = "QATAR", NiceName = "Qatar", Iso3 = "QAT", NumCode = 634, Active = true, PhoneCode = 974 },
                new Country { Id = 175, Iso = "RE", Name = "REUNION", NiceName = "Reunion", Iso3 = "REU", NumCode = 638, Active = true, PhoneCode = 262 },
                new Country { Id = 176, Iso = "RO", Name = "ROMANIA", NiceName = "Romania", Iso3 = "ROM", NumCode = 642, Active = true, PhoneCode = 40 },
                new Country { Id = 177, Iso = "RU", Name = "RUSSIAN FEDERATION", NiceName = "Russian Federation", Iso3 = "RUS", NumCode = 643, Active = true, PhoneCode = 70 },
                new Country { Id = 178, Iso = "RW", Name = "RWANDA", NiceName = "Rwanda", Iso3 = "RWA", NumCode = 646, Active = true, PhoneCode = 250 },
                new Country { Id = 179, Iso = "SH", Name = "SAINT HELENA", NiceName = "Saint Helena", Iso3 = "SHN", NumCode = 654, Active = true, PhoneCode = 290 },
                new Country { Id = 180, Iso = "KN", Name = "SAINT KITTS AND NEVIS", NiceName = "Saint Kitts and Nevis", Iso3 = "KNA", NumCode = 659, Active = true, PhoneCode = 1869 },
                new Country { Id = 181, Iso = "LC", Name = "SAINT LUCIA", NiceName = "Saint Lucia", Iso3 = "LCA", NumCode = 662, Active = true, PhoneCode = 1758 },
                new Country { Id = 182, Iso = "PM", Name = "SAINT PIERRE AND MIQUELON", NiceName = "Saint Pierre and Miquelon", Iso3 = "SPM", NumCode = 666, Active = true, PhoneCode = 508 },
                new Country { Id = 183, Iso = "VC", Name = "SAINT VINCENT AND THE GRENADINES", NiceName = "Saint Vincent and the Grenadines", Iso3 = "VCT", NumCode = 670, Active = true, PhoneCode = 1784 },
                new Country { Id = 184, Iso = "WS", Name = "SAMOA", NiceName = "Samoa", Iso3 = "WSM", NumCode = 882, Active = true, PhoneCode = 684 },
                new Country { Id = 185, Iso = "SM", Name = "SAN MARINO", NiceName = "San Marino", Iso3 = "SMR", NumCode = 674, Active = true, PhoneCode = 378 },
                new Country { Id = 186, Iso = "ST", Name = "SAO TOME AND PRINCIPE", NiceName = "Sao Tome and Principe", Iso3 = "STP", NumCode = 678, Active = true, PhoneCode = 239 },
                new Country { Id = 187, Iso = "SA", Name = "SAUDI ARABIA", NiceName = "Saudi Arabia", Iso3 = "SAU", NumCode = 682, Active = true, PhoneCode = 966 },
                new Country { Id = 188, Iso = "SN", Name = "SENEGAL", NiceName = "Senegal", Iso3 = "SEN", NumCode = 686, Active = true, PhoneCode = 221 },
                new Country { Id = 189, Iso = "CS", Name = "SERBIA AND MONTENEGRO", NiceName = "Serbia and Montenegro", Iso3 =null, NumCode =0, Active = true, PhoneCode = 381 },
                new Country { Id = 190, Iso = "SC", Name = "SEYCHELLES", NiceName = "Seychelles", Iso3 = "SYC", NumCode = 690, Active = true, PhoneCode = 248 },
                new Country { Id = 191, Iso = "SL", Name = "SIERRA LEONE", NiceName = "Sierra Leone", Iso3 = "SLE", NumCode = 694, Active = true, PhoneCode = 232 },
                new Country { Id = 192, Iso = "SG", Name = "SINGAPORE", NiceName = "Singapore", Iso3 = "SGP", NumCode = 702, Active = true, PhoneCode = 65 },
                new Country { Id = 193, Iso = "SK", Name = "SLOVAKIA", NiceName = "Slovakia", Iso3 = "SVK", NumCode = 703, Active = true, PhoneCode = 421 },
                new Country { Id = 194, Iso = "SI", Name = "SLOVENIA", NiceName = "Slovenia", Iso3 = "SVN", NumCode = 705, Active = true, PhoneCode = 386 },
                new Country { Id = 195, Iso = "SB", Name = "SOLOMON ISLANDS", NiceName = "Solomon Islands", Iso3 = "SLB", NumCode = 90, Active = true, PhoneCode = 677 },
                new Country { Id = 196, Iso = "SO", Name = "SOMALIA", NiceName = "Somalia", Iso3 = "SOM", NumCode = 706, Active = true, PhoneCode = 252 },
                new Country { Id = 197, Iso = "ZA", Name = "SOUTH AFRICA", NiceName = "South Africa", Iso3 = "ZAF", NumCode = 710, Active = true, PhoneCode = 27 },
                new Country { Id = 198, Iso = "GS", Name = "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", NiceName = "South Georgia and the South Sandwich Islands", Iso3 =null, NumCode =0, Active = true, PhoneCode = 0 },
                new Country { Id = 199, Iso = "ES", Name = "SPAIN", NiceName = "Spain", Iso3 = "ESP", NumCode = 724, Active = true, PhoneCode = 34 },
                new Country { Id = 200, Iso = "LK", Name = "SRI LANKA", NiceName = "Sri Lanka", Iso3 = "LKA", NumCode = 144, Active = true, PhoneCode = 94 },
                new Country { Id = 201, Iso = "SD", Name = "SUDAN", NiceName = "Sudan", Iso3 = "SDN", NumCode = 736, Active = true, PhoneCode = 249 },
                new Country { Id = 202, Iso = "SR", Name = "SURINAME", NiceName = "Suriname", Iso3 = "SUR", NumCode = 740, Active = true, PhoneCode = 597 },
                new Country { Id = 203, Iso = "SJ", Name = "SVALBARD AND JAN MAYEN", NiceName = "Svalbard and Jan Mayen", Iso3 = "SJM", NumCode = 744, Active = true, PhoneCode = 47 },
                new Country { Id = 204, Iso = "SZ", Name = "SWAZILAND", NiceName = "Swaziland", Iso3 = "SWZ", NumCode = 748, Active = true, PhoneCode = 268 },
                new Country { Id = 205, Iso = "SE", Name = "SWEDEN", NiceName = "Sweden", Iso3 = "SWE", NumCode = 752, Active = true, PhoneCode = 46 },
                new Country { Id = 206, Iso = "CH", Name = "SWITZERLAND", NiceName = "Switzerland", Iso3 = "CHE",NumCode= 756, Active = true, PhoneCode = 41 },
                new Country { Id = 207, Iso = "SY", Name = "SYRIAN ARAB REPUBLIC", NiceName = "Syrian Arab Republic", Iso3 = "SYR", NumCode = 760, Active = true, PhoneCode = 963 },
                new Country { Id = 208, Iso = "TW", Name = "TAIWAN, PROVINCE OF CHINA", NiceName = "Taiwan, Province of China", Iso3 = "TWN", NumCode = 158, Active = true, PhoneCode = 886 },
                new Country { Id = 209, Iso = "TJ", Name = "TAJIKISTAN", NiceName = "Tajikistan", Iso3 = "TJK", NumCode = 762, Active = true, PhoneCode = 992 },
                new Country { Id = 210, Iso = "TZ", Name = "TANZANIA, UNITED REPUBLIC OF", NiceName = "Tanzania, United Republic of", Iso3 = "TZA", NumCode = 834, Active = true, PhoneCode = 255 },
                new Country { Id = 211, Iso = "TH", Name = "THAILAND", NiceName = "Thailand", Iso3 = "THA", NumCode = 764, Active = true, PhoneCode = 66 },
                new Country { Id = 212, Iso = "TL", Name = "TIMOR-LESTE", NiceName = "Timor-Leste", Iso3 =null, NumCode =0, Active = true, PhoneCode = 670 },
                new Country { Id = 213, Iso = "TG", Name = "TOGO", NiceName = "Togo", Iso3 = "TGO", NumCode = 768, Active = true, PhoneCode = 228 },
                new Country { Id = 214, Iso = "TK", Name = "TOKELAU", NiceName = "Tokelau", Iso3 = "TKL", NumCode = 772, Active = true, PhoneCode = 690 },
                new Country { Id = 215, Iso = "TO", Name = "TONGA", NiceName = "Tonga", Iso3 = "TON", NumCode = 776, Active = true, PhoneCode = 676 },
                new Country { Id = 216, Iso = "TT", Name = "TRINIDAD AND TOBAGO", NiceName = "Trinidad and Tobago", Iso3 = "TTO", NumCode = 780, Active = true, PhoneCode = 1868 },
                new Country { Id = 217, Iso = "TN", Name = "TUNISIA", NiceName = "Tunisia", Iso3 = "TUN", NumCode = 788, Active = true, PhoneCode = 216 },
                new Country { Id = 218, Iso = "TR", Name = "TURKEY", NiceName = "Turkey", Iso3 = "TUR", NumCode = 792, Active = true, PhoneCode = 90 },
                new Country { Id = 219, Iso = "TM", Name = "TURKMENISTAN", NiceName = "Turkmenistan", Iso3 = "TKM", NumCode = 795, Active = true, PhoneCode = 7370 },
                new Country { Id = 220, Iso = "TC", Name = "TURKS AND CAICOS ISLANDS", NiceName = "Turks and Caicos Islands", Iso3 = "TCA", NumCode = 796, Active = true, PhoneCode = 1649 },
                new Country { Id = 221, Iso = "TV", Name = "TUVALU", NiceName = "Tuvalu", Iso3 = "TUV", NumCode = 798, Active = true, PhoneCode = 688 },
                new Country { Id = 222, Iso = "UG", Name = "UGANDA", NiceName = "Uganda", Iso3 = "UGA", NumCode = 800, Active = true, PhoneCode = 256 },
                new Country { Id = 223, Iso = "UA", Name = "UKRAINE", NiceName = "Ukraine", Iso3 = "UKR", NumCode = 804, Active = true, PhoneCode = 380 },
                new Country { Id = 224, Iso = "AE", Name = "UNITED ARAB EMIRATES", NiceName = "United Arab Emirates", Iso3 = "ARE", NumCode = 784, Active = true, PhoneCode = 971 },
                new Country { Id = 225, Iso = "GB", Name = "UNITED KINGDOM", NiceName = "United Kingdom", Iso3 = "GBR", NumCode = 826, Active = true, PhoneCode = 44 },
                new Country { Id = 226, Iso = "US", Name = "UNITED STATES", NiceName = "United States", Iso3 = "USA", NumCode = 840, Active = true, PhoneCode = 1 },
                new Country { Id = 227, Iso = "UM", Name = "UNITED STATES MINOR OUTLYING ISLANDS", NiceName = "United States Minor Outlying Islands", Iso3 =null, NumCode =0, Active = true, PhoneCode = 1 },
                new Country { Id = 228, Iso = "UY", Name = "URUGUAY", NiceName = "Uruguay", Iso3 = "URY", NumCode = 858, Active = true, PhoneCode = 598 },
                new Country { Id = 229, Iso = "UZ", Name = "UZBEKISTAN", NiceName = "Uzbekistan", Iso3 = "UZB", NumCode = 860, Active = true, PhoneCode = 998 },
                new Country { Id = 230, Iso = "VU", Name = "VANUATU", NiceName = "Vanuatu", Iso3 = "VUT", NumCode = 548, Active = true, PhoneCode = 678 },
                new Country { Id = 231, Iso = "VE", Name = "VENEZUELA", NiceName = "Venezuela", Iso3 = "VEN", NumCode = 862, Active = true, PhoneCode = 58 },
                new Country { Id = 232, Iso = "VN", Name = "VIET NAM", NiceName = "Viet Nam", Iso3 = "VNM", NumCode = 704, Active = true, PhoneCode = 84 },
                new Country { Id = 233, Iso = "VG", Name = "VIRGIN ISLANDS, BRITISH", NiceName = "Virgin Islands, British", Iso3 = "VGB", NumCode = 92, Active = true, PhoneCode = 1284 },
                new Country { Id = 234, Iso = "VI", Name = "VIRGIN ISLANDS, U.S.", NiceName = "Virgin Islands, U.s.", Iso3 = "VIR", NumCode = 850, Active = true, PhoneCode = 1340 },
                new Country { Id = 235, Iso = "WF", Name = "WALLIS AND FUTUNA", NiceName = "Wallis and Futuna", Iso3 = "WLF", NumCode = 876, Active = true, PhoneCode = 681 },
                new Country { Id = 236, Iso = "EH", Name = "WESTERN SAHARA", NiceName = "Western Sahara", Iso3 = "ESH", NumCode = 732, Active = true, PhoneCode = 212 },
                new Country { Id = 237, Iso = "YE", Name = "YEMEN", NiceName = "Yemen", Iso3 = "YEM", NumCode = 887, Active = true, PhoneCode = 967 },
                new Country { Id = 238, Iso = "ZM", Name = "ZAMBIA", NiceName = "Zambia", Iso3 = "ZMB", NumCode = 894, Active = true, PhoneCode = 260 },
                new Country { Id = 239, Iso = "ZW", Name = "ZIMBABWE", NiceName = "Zimbabwe", Iso3 = "ZWE", NumCode = 716, Active = true, PhoneCode = 263 }
            );
        }
    }
}
